parameters:
#    ftc56_user.example.class: FTC56\userBundle\Example

services:
#    ftc56_user.example:
#        class: %ftc56_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
