parameters:
#    ftc56_blog.example.class: FTC56\BlogBundle\Example

services:
#    ftc56_blog.example:
#        class: %ftc56_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
